version: '3.8'

services:
  web:
    image: registry.digitalocean.com/nbi/web-prod:latest
    command: gunicorn nbi.wsgi:application --timeout 200 --bind 0.0.0.0:8000 --log-level debug
    container_name: web
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db

  db:
    image: registry.digitalocean.com/nbi/db-prod:latest
    command: postgres -c log_statement=all -c max_wal_size=2GB
    container_name: db
    volumes:
      - nbi-data-prod:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env

  redis:
    image: redis:bullseye
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru 
    container_name: cache
    expose:
      - 6379
    restart: always
    volumes:
      - redis-data-prod:/data

  express:
    container_name: express
    image: registry.digitalocean.com/nbi/express-prod:latest
    ports:
      - 3000:3000
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis


volumes:
  nbi-data-prod:
  redis-data-prod:

networks:
  default:
    name: nbi
