version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn nbi.wsgi:application --timeout 200 --bind 0.0.0.0:8000 --log-level debug
    container_name: web
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    restart: always
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile.prod.db
    command: postgres -c log_statement=all -c max_wal_size=2GB
    container_name: db
    volumes:
      - nbi-data-prod:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env.prod

  express:
    build:
      context: ./express-redis
      dockerfile: Dockerfile.prod
    container_name: express
    volumes:
      - ./express-redis/:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - ./.env.prod
    restart: always


volumes:
  nbi-data-prod:

networks:
  default:
    name: nbi
