version: '3.8'

services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/django/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile.db
    command: postgres -c log_statement=all -c max_wal_size=2GB
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    env_file:
      - ./.env.dev

volumes:
  db-data:
