version: '3.8'

services:
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - ./django/:/usr/src/django/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile.db
    command: postgres -c log_statement=all -c max_wal_size=2GB
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    env_file:
      - ./.env.dev

  redis:
    image: redis:bullseye
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru 
    container_name: cache
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  express:
    build: ./express-redis
    command: npm start
    container_name: express
    volumes:
      - ./express-redis/:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev

  preact:
    build: ./preact
    command: npm run dev
    container_name: preact
    ports:
      - 8080: 8080
    env_file:
      - ./.env.dev

volumes:
  db-data:
  redis-data:
