#------------------>Production image
FROM node:16-alpine
RUN apk add dumb-init
RUN apk add sudo
RUN apk add curl

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install 
COPY . .
CMD ["dumb-init", "node", "server.js"]

