#------------------>Build image
FROM node:bullseye-slim AS build
WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
RUN npm ci --only=production

#------------------>Production image
FROM node:lts-alpine
RUN apk add dumb-init
RUN apk add sudo
RUN apk add curl
ENV NODE_ENV production
USER node
WORKDIR /usr/src/app
COPY --chown=node:node --from=build /usr/src/app/node_modules /usr/src/app/node_modules
COPY --chown=node:node . /usr/src/app
CMD ["dumb-init", "node", "server.js"]