#!/bin/bash

psql -U $POSTGRES_USER -d $POSTGRES_DB <<EOF
CREATE USER $SQL_USER WITH PASSWORD '$SQL_PASSWORD';
GRANT CONNECT ON DATABASE $SQL_DATABASE TO $SQL_USER;
GRANT USAGE ON SCHEMA public TO $SQL_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $SQL_USER;
EOF
