FROM postgres:13.0-alpine
ADD ./db/small_nbi.sql /docker-entrypoint-initdb.d

# to load from command line
# docker exec -i ${CONTAINER_NAME} psql -U admin -d nbi_test < small_nbi.sql
# table name is 'small_nbi', schema is 'public'