FROM postgis/postgis:14-master

# FROM postgres:13.0-alpine

RUN mkdir /db

ADD ./db/2020AllRecordsDelimitedAllStatesClean.csv /db

ADD ./db/fk_csvs/*.csv /db/fk_csvs/

ADD ./db/01-load_db.sql /docker-entrypoint-initdb.d
ADD ./db/02-create_user.sh /docker-entrypoint-initdb.d

RUN chown postgres:postgres /db/*
RUN chown postgres:postgres /db/fk_csvs/*

