FROM postgis/postgis:14-master

RUN mkdir /db

ADD ./2024AllRecordsDelimitedAllStatesClean.csv /db

ADD ./fk_csvs/*.csv /db/fk_csvs/

ADD ./01-load_db.sql /docker-entrypoint-initdb.d
ADD ./02-create_user.sh /docker-entrypoint-initdb.d

RUN chown postgres:postgres /db/*
RUN chown postgres:postgres /db/fk_csvs/*

