FROM postgres:13.0-alpine

ADD ./db/BadCleaned.csv /docker-entrypoint-initdb.d

ADD ./db/fk_csvs/*.csv /docker-entrypoint-initdb.d/fk_csvs/

ADD ./db/load_db.sql /docker-entrypoint-initdb.d

RUN chown postgres:postgres /docker-entrypoint-initdb.d/*
RUN chown postgres:postgres /docker-entrypoint-initdb.d/fk_csvs/*

# ADD ./db/load_db.sql /docker-entrypoint-initdb.d
# ADD ./db/small_nbi.sql /docker-entrypoint-initdb.d

# to load from command line
# docker exec -i ${CONTAINER_NAME} psql -U admin -d nbi_test < small_nbi.sql
# table name is 'small_nbi', schema is 'public'