CREATE INDEX structure_type ON nbi ("STRUCTURE_TYPE_043B");
CREATE INDEX rated ON nbi ("LOWEST_RATING");
CREATE INDEX bridge_only ON NBI ("STRUCTURE_TYPE_043B") WHERE NOT ("STRUCTURE_TYPE_043B"=00 OR "STRUCTURE_TYPE_043B"=19 OR "STRUCTURE_TYPE_043B"=18)
